version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - backend-challenge

  postgres:
    image: postgres:13.15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saipul1452
      POSTGRES_DB: online_store
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-challenge

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saipul1452
      POSTGRES_DB: online_store
    networks:
      - backend-challenge

networks:
  backend-challenge:
    driver: bridge

volumes:
  postgres_data:
