version: "3"
services:
  db:
    image: postgres:13
    container_name: online_store_postgres
    environment:
      POSTGRES_DB: online_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saipul1452
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: online_store_redis
    ports:
      - "6379:6379"
